### ISSUE TITLE
slide

### ISSUE THREAD

**Issue by tarukosu** [tarukosu/blog#2]
https://docs.google.com/presentation/d/15XfIauoetbpGLohVsH9FkTx-o7E12dRtqkAnZS_xal4/edit?usp=sharing

**Comment by aginika** [comment]
nice

**Comment by mmurooka** [comment]
nice2

**Comment by tarukosu** [comment]
this slide is used in rookie training

**Comment by aginika** [comment]
Do you enjoy your work?

**Comment by tarukosu** [comment]
Yes! I want to talk with you about my work and your great work in DRC.

**Comment by aginika** [comment]
Sounds Great!!

I think I did work at Amazon Picking Challenge rather than DRC.
But result wasn't good :(

I decided my job whose HQ is at the Shin-Osaka, so I need to move next year.
