### ISSUE TITLE
Request about Ros and Hololens

### ISSUE THREAD

**Issue by linhdoan8** [tarukosu/blog#3]
Dear @tarukosu,

Iam a student from Germany and working on my thesis with ROS Sharp and Hololens.
Gladly, I saw that you have achieved visualization of Rviz into Hololens which also intrests me. 
I am refering to your blog and the videos of yours e.g. : [RvizonHololens](https://www.youtube.com/watch?v=-hQuUrULlUU)

Currently I am also working on bringing Rviz to the hololens. I would like to know how you do the coordinate transformation between hololens and robot, in other words how can you detect the robots pose and position with the hololens. 

Now my approach is to use Aruco Markers from the openCV library but your approach seems to be alot better. I would be very amazed if we could get in contact with each other and hope for your reply!

P.S.: Sorry to open an issue here, but I couldnt find another way to contact you personally ^^

Best regards

**Comment by tarukosu** [comment]
Unfortunately, I don't detect the robots pose and position.
I aligned a real robot and a virtual robot with gesture.
Joint angles of the robot are sent to HoloLens and a robot model in HoloLens moves accordingly.

Your approach is better than my approach. I hope I can see your demo!

**Comment by linhdoan8** [comment]
Hi Tarukosu,
thanks for your reply! My approach with markers is working but is not optimal especially when you are far away.  So I will test another approach and will show you the demo vid as soon as the project is done! 
Best regards!
